// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operations.Infrastructure.Persistence;

#nullable disable

namespace Operations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    partial class OperationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Models.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Models.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages", "operations");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Aggregates.Flight.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClientFlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClientFlightId")
                        .IsUnique()
                        .HasFilter("[ClientFlightId] IS NOT NULL");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("Flights", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Aggregates.WorkOrder.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AircraftTailNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClientMutationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfirmedFlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CustomerSignature")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("CustomerSignature");

                    b.Property<Guid?>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FlightNumber");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("MarkedForDeletionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WorkOrderNo")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("WorkOrderNo");

                    b.HasKey("Id");

                    b.HasIndex("ClientMutationId")
                        .IsUnique()
                        .HasFilter("[ClientMutationId] IS NOT NULL");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FlightId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("FlightId", "Status");

                    b.HasIndex("Status", "MarkedForDeletionAt");

                    b.HasIndex("Status", "UpdatedAt");

                    b.HasIndex("FlightId", "CreatedByEmployeeId", "Status");

                    b.ToTable("WorkOrders", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.FlightAssignedEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightAssignments", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.FlightService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightServices", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.FlightWorkOrderAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("FlightId", "WorkOrderId")
                        .IsUnique();

                    b.ToTable("FlightWorkOrderAttachments", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderServiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ReturnToRamp")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkOrderId", "From");

                    b.ToTable("WorkOrderServiceLines", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ReturnToRamp")
                        .HasColumnType("bit");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderTasks", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkOrderTaskAttachments", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkOrderTaskEmployees", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskGeneralSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkOrderTaskGeneralSupports", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkOrderTaskMaterials", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskTool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkOrderTaskTools", "operations");
                });

            modelBuilder.Entity("Operations.Infrastructure.Persistence.StationWorkOrderCounter", b =>
                {
                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.HasKey("StationId");

                    b.ToTable("StationWorkOrderCounters", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Aggregates.Flight.Flight", b =>
                {
                    b.OwnsOne("Core.Contracts.Features.AircraftType.AircraftTypeSnapshot", "AircraftType", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AircraftTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AircraftTypeId");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AircraftTypeModel");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Core.Contracts.Features.Customer.CustomerSnapshot", "Customer", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CustomerId");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("CustomerIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CustomerName");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Core.Contracts.Features.OperationType.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("OperationTypeName");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationTypeId");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.ScheduledTime", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Sta")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Sta");

                            b1.Property<DateTimeOffset>("Std")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Std");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Core.Contracts.Features.Station.StationSnapshot", "Station", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("StationIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("StationName");

                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StationId");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.FlightNumber", "FlightNumber", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("FlightNumber");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.WorkOrderSnapshot", "AcceptedWorkOrder", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AcceptedWorkOrderId");

                            b1.Property<string>("WorkOrderNumber")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("AcceptedWorkOrderNumber");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.Navigation("AcceptedWorkOrder");

                    b.Navigation("AircraftType");

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("FlightNumber")
                        .IsRequired();

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Station")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Aggregates.WorkOrder.WorkOrder", b =>
                {
                    b.OwnsOne("Core.Contracts.Features.AircraftType.AircraftTypeSnapshot", "AircraftType", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AircraftTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AircraftTypeId");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AircraftTypeModel");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Core.Contracts.Features.Customer.CustomerSnapshot", "Customer", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CustomerId");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("CustomerIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CustomerName");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Core.Contracts.Features.OperationType.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("OperationTypeName");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationTypeId");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.ScheduledTime", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Sta")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Sta");

                            b1.Property<DateTimeOffset>("Std")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Std");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Core.Contracts.Features.Station.StationSnapshot", "Station", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("StationIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("StationName");

                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StationId");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.ActualTime", "TimesActual", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Ata")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Ata");

                            b1.Property<DateTimeOffset>("Atd")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Atd");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.Navigation("AircraftType");

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Station")
                        .IsRequired();

                    b.Navigation("TimesActual");
                });

            modelBuilder.Entity("Operations.Domain.Entities.FlightAssignedEmployee", b =>
                {
                    b.HasOne("Operations.Domain.Aggregates.Flight.Flight", null)
                        .WithMany("AssignedEmployees")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Contracts.Features.Employee.EmployeeSnapshot", "Employee", b1 =>
                        {
                            b1.Property<Guid>("FlightAssignedEmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("EmployeeId");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("EmployeeFullName");

                            b1.HasKey("FlightAssignedEmployeeId");

                            b1.ToTable("FlightAssignments", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightAssignedEmployeeId");

                            b1.OwnsOne("Core.Contracts.Features.ManpowerType.ManpowerTypeSnapshot", "ManpowerTypeSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeSnapshotFlightAssignedEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ManpowerTypeId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("EmployeeManpowerTypeId");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)")
                                        .HasColumnName("EmployeeManpowerTypeName");

                                    b2.HasKey("EmployeeSnapshotFlightAssignedEmployeeId");

                                    b2.ToTable("FlightAssignments", "operations");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeSnapshotFlightAssignedEmployeeId");
                                });

                            b1.OwnsOne("Core.Contracts.Features.Station.StationSnapshot", "StationSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeSnapshotFlightAssignedEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("IataCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("EmployeeStationIataCode");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)")
                                        .HasColumnName("EmployeeStationName");

                                    b2.Property<Guid>("StationId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("EmployeeStationId");

                                    b2.HasKey("EmployeeSnapshotFlightAssignedEmployeeId");

                                    b2.ToTable("FlightAssignments", "operations");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeSnapshotFlightAssignedEmployeeId");
                                });

                            b1.Navigation("ManpowerTypeSnapshot")
                                .IsRequired();

                            b1.Navigation("StationSnapshot")
                                .IsRequired();
                        });

                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.FlightService", b =>
                {
                    b.HasOne("Operations.Domain.Aggregates.Flight.Flight", null)
                        .WithMany("Services")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Contracts.Features.Service.ServiceSnapshot", "Service", b1 =>
                        {
                            b1.Property<Guid>("FlightServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsAog")
                                .HasColumnType("bit")
                                .HasColumnName("IsAog");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("ServiceName");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ServiceId");

                            b1.HasKey("FlightServiceId");

                            b1.ToTable("FlightServices", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightServiceId");
                        });

                    b.Navigation("Service")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.FlightWorkOrderAttachment", b =>
                {
                    b.HasOne("Operations.Domain.Aggregates.Flight.Flight", null)
                        .WithMany("AttachedWorkOrderLinks")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderServiceLine", b =>
                {
                    b.HasOne("Operations.Domain.Aggregates.WorkOrder.WorkOrder", null)
                        .WithMany("_serviceLines")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Contracts.Features.Employee.EmployeeSnapshot", "Employee", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderServiceLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("EmployeeId");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("EmployeeFullName");

                            b1.HasKey("WorkOrderServiceLineId");

                            b1.ToTable("WorkOrderServiceLines", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderServiceLineId");

                            b1.OwnsOne("Core.Contracts.Features.ManpowerType.ManpowerTypeSnapshot", "ManpowerTypeSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeSnapshotWorkOrderServiceLineId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ManpowerTypeId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("EmployeeManpowerTypeId");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)")
                                        .HasColumnName("EmployeeManpowerTypeName");

                                    b2.HasKey("EmployeeSnapshotWorkOrderServiceLineId");

                                    b2.ToTable("WorkOrderServiceLines", "operations");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeSnapshotWorkOrderServiceLineId");
                                });

                            b1.OwnsOne("Core.Contracts.Features.Station.StationSnapshot", "StationSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeSnapshotWorkOrderServiceLineId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("IataCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("EmployeeStationIataCode");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)")
                                        .HasColumnName("EmployeeStationName");

                                    b2.Property<Guid>("StationId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("EmployeeStationId");

                                    b2.HasKey("EmployeeSnapshotWorkOrderServiceLineId");

                                    b2.ToTable("WorkOrderServiceLines", "operations");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeSnapshotWorkOrderServiceLineId");
                                });

                            b1.Navigation("ManpowerTypeSnapshot")
                                .IsRequired();

                            b1.Navigation("StationSnapshot")
                                .IsRequired();
                        });

                    b.OwnsOne("Core.Contracts.Features.Service.ServiceSnapshot", "Service", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderServiceLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsAog")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("ServiceName");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ServiceId");

                            b1.HasKey("WorkOrderServiceLineId");

                            b1.ToTable("WorkOrderServiceLines", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderServiceLineId");
                        });

                    b.Navigation("Employee")
                        .IsRequired();

                    b.Navigation("Service")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTask", b =>
                {
                    b.HasOne("Operations.Domain.Aggregates.WorkOrder.WorkOrder", null)
                        .WithMany("_tasks")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskAttachment", b =>
                {
                    b.HasOne("Operations.Domain.Entities.WorkOrderTask", null)
                        .WithMany("_attachments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskEmployee", b =>
                {
                    b.HasOne("Operations.Domain.Entities.WorkOrderTask", null)
                        .WithMany("_employees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Contracts.Features.Employee.EmployeeSnapshot", "Employee", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskEmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("EmployeeId");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("EmployeeFullName");

                            b1.HasKey("WorkOrderTaskEmployeeId");

                            b1.ToTable("WorkOrderTaskEmployees", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskEmployeeId");

                            b1.OwnsOne("Core.Contracts.Features.ManpowerType.ManpowerTypeSnapshot", "ManpowerTypeSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeSnapshotWorkOrderTaskEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ManpowerTypeId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("EmployeeManpowerTypeId");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)")
                                        .HasColumnName("EmployeeManpowerTypeName");

                                    b2.HasKey("EmployeeSnapshotWorkOrderTaskEmployeeId");

                                    b2.ToTable("WorkOrderTaskEmployees", "operations");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeSnapshotWorkOrderTaskEmployeeId");
                                });

                            b1.OwnsOne("Core.Contracts.Features.Station.StationSnapshot", "StationSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeSnapshotWorkOrderTaskEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("IataCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("EmployeeStationIataCode");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)")
                                        .HasColumnName("EmployeeStationName");

                                    b2.Property<Guid>("StationId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("EmployeeStationId");

                                    b2.HasKey("EmployeeSnapshotWorkOrderTaskEmployeeId");

                                    b2.ToTable("WorkOrderTaskEmployees", "operations");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeSnapshotWorkOrderTaskEmployeeId");
                                });

                            b1.Navigation("ManpowerTypeSnapshot")
                                .IsRequired();

                            b1.Navigation("StationSnapshot")
                                .IsRequired();
                        });

                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskGeneralSupport", b =>
                {
                    b.HasOne("Operations.Domain.Entities.WorkOrderTask", null)
                        .WithMany("_generalSupports")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Store.Contracts.Features.GeneralSupport.GeneralSupportSnapshot", "GeneralSupport", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskGeneralSupportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GeneralSupportId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("GeneralSupportId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("GeneralSupportName");

                            b1.HasKey("WorkOrderTaskGeneralSupportId");

                            b1.ToTable("WorkOrderTaskGeneralSupports", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskGeneralSupportId");
                        });

                    b.Navigation("GeneralSupport")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskMaterial", b =>
                {
                    b.HasOne("Operations.Domain.Entities.WorkOrderTask", null)
                        .WithMany("_materials")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Store.Contracts.Features.Material.MaterialSnapshot", "Material", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskMaterialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MaterialId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("MaterialId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("MaterialName");

                            b1.HasKey("WorkOrderTaskMaterialId");

                            b1.ToTable("WorkOrderTaskMaterials", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskMaterialId");
                        });

                    b.Navigation("Material")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTaskTool", b =>
                {
                    b.HasOne("Operations.Domain.Entities.WorkOrderTask", null)
                        .WithMany("_tools")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Store.Contracts.Features.Tool.ToolSnapshot", "Tool", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("ToolName");

                            b1.Property<Guid>("ToolId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ToolId");

                            b1.HasKey("WorkOrderTaskToolId");

                            b1.ToTable("WorkOrderTaskTools", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskToolId");
                        });

                    b.Navigation("Tool")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Aggregates.Flight.Flight", b =>
                {
                    b.Navigation("AssignedEmployees");

                    b.Navigation("AttachedWorkOrderLinks");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Operations.Domain.Aggregates.WorkOrder.WorkOrder", b =>
                {
                    b.Navigation("_serviceLines");

                    b.Navigation("_tasks");
                });

            modelBuilder.Entity("Operations.Domain.Entities.WorkOrderTask", b =>
                {
                    b.Navigation("_attachments");

                    b.Navigation("_employees");

                    b.Navigation("_generalSupports");

                    b.Navigation("_materials");

                    b.Navigation("_tools");
                });
#pragma warning restore 612, 618
        }
    }
}
