// <auto-generated />
using System;
using Contracts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contracts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContractsDbContext))]
    partial class ContractsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Models.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Models.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages", "contracts");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.CancellationBracket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "SortOrder");

                    b.ToTable("CancellationBrackets", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ApplyVat")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Attachment")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("CancellationBasis")
                        .HasColumnType("int");

                    b.Property<int>("CancellationChargeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DebriefRequired")
                        .HasColumnType("bit");

                    b.Property<int>("DelayBasis")
                        .HasColumnType("int");

                    b.Property<int>("DelayChargeType")
                        .HasColumnType("int");

                    b.Property<int>("DelayType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastExpiringSoonNotificationAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTerms")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Contracts", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.ContractAdvancePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "OperationTypeId")
                        .IsUnique()
                        .HasDatabaseName("UX_ContractAdvancePayments_Contract_OperationType");

                    b.ToTable("ContractAdvancePayments", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.ContractOperationType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractOperationTypes", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.ContractStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractStations", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.DelayBracket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "SortOrder");

                    b.ToTable("DelayBrackets", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractGeneralSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Basis")
                        .HasColumnType("int");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "OperationTypeId");

                    b.ToTable("ContractGeneralSupports", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractManpower", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Basis")
                        .HasColumnType("int");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "OperationTypeId");

                    b.ToTable("ContractManpowers", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Basis")
                        .HasColumnType("int");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "OperationTypeId");

                    b.ToTable("ContractMaterials", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Basis")
                        .HasColumnType("int");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "OperationTypeId");

                    b.ToTable("ContractServices", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractTool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Basis")
                        .HasColumnType("int");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "OperationTypeId");

                    b.ToTable("ContractTools", "contracts");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.CancellationBracket", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("CancellationBrackets")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Contract", b =>
                {
                    b.OwnsOne("Contracts.Domain.Aggregates.Contract.Termination", "Termination", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("Termination_AtUtc");

                            b1.Property<Guid>("ByUserId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Termination_ByUserId");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Termination_Reason");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.ContractNo", "ContractNo", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ContractNo");

                            b1.HasKey("ContractId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Contracts", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.ContractPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ExpiryAlertDays")
                                .HasColumnType("int")
                                .HasColumnName("Period_ExpiryAlertDays");

                            b1.Property<int?>("ExpiryAlertInterval")
                                .HasColumnType("int")
                                .HasColumnName("Period_ExpiryAlertInterval");

                            b1.Property<DateTimeOffset>("ExpiryDate")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Period_ExpiryDate");

                            b1.Property<DateTimeOffset>("StartDate")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Period_StartDate");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.CurrencySnapshot", "Currency", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency_Code");

                            b1.Property<Guid>("CurrencyId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Currency_CurrencyId");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.CustomerSnapshot", "Customer", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Customer_CustomerId");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Customer_IataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Customer_Name");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.FeesAndRates", "FeesAndRates", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Fee", "AdminFee", b2 =>
                                {
                                    b2.Property<Guid>("FeesAndRatesContractId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Type")
                                        .HasColumnType("int")
                                        .HasColumnName("Fees_Admin_Type");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Fees_Admin_Value");

                                    b2.HasKey("FeesAndRatesContractId");

                                    b2.ToTable("Contracts", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("FeesAndRatesContractId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Fee", "DisbursementFee", b2 =>
                                {
                                    b2.Property<Guid>("FeesAndRatesContractId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Type")
                                        .HasColumnType("int")
                                        .HasColumnName("Fees_Disbursement_Type");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Fees_Disbursement_Value");

                                    b2.HasKey("FeesAndRatesContractId");

                                    b2.ToTable("Contracts", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("FeesAndRatesContractId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Fee", "HolidayFee", b2 =>
                                {
                                    b2.Property<Guid>("FeesAndRatesContractId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Type")
                                        .HasColumnType("int")
                                        .HasColumnName("Fees_Holiday_Type");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Fees_Holiday_Value");

                                    b2.HasKey("FeesAndRatesContractId");

                                    b2.ToTable("Contracts", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("FeesAndRatesContractId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Fee", "NightFee", b2 =>
                                {
                                    b2.Property<Guid>("FeesAndRatesContractId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Type")
                                        .HasColumnType("int")
                                        .HasColumnName("Fees_Night_Type");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Fees_Night_Value");

                                    b2.HasKey("FeesAndRatesContractId");

                                    b2.ToTable("Contracts", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("FeesAndRatesContractId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Fee", "OtherDiscount", b2 =>
                                {
                                    b2.Property<Guid>("FeesAndRatesContractId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Type")
                                        .HasColumnType("int")
                                        .HasColumnName("Fees_Other_Type");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Fees_Other_Value");

                                    b2.HasKey("FeesAndRatesContractId");

                                    b2.ToTable("Contracts", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("FeesAndRatesContractId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Fee", "ReturnToRampDiscount", b2 =>
                                {
                                    b2.Property<Guid>("FeesAndRatesContractId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Type")
                                        .HasColumnType("int")
                                        .HasColumnName("Fees_ReturnToRamp_Type");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Fees_ReturnToRamp_Value");

                                    b2.HasKey("FeesAndRatesContractId");

                                    b2.ToTable("Contracts", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("FeesAndRatesContractId");
                                });

                            b1.Navigation("AdminFee")
                                .IsRequired();

                            b1.Navigation("DisbursementFee")
                                .IsRequired();

                            b1.Navigation("HolidayFee")
                                .IsRequired();

                            b1.Navigation("NightFee")
                                .IsRequired();

                            b1.Navigation("OtherDiscount")
                                .IsRequired();

                            b1.Navigation("ReturnToRampDiscount")
                                .IsRequired();
                        });

                    b.Navigation("ContractNo")
                        .IsRequired();

                    b.Navigation("Currency")
                        .IsRequired();

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("FeesAndRates")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Termination");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.ContractAdvancePayment", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("AdvancePayments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Contracts.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("ContractAdvancePaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationType_Name");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationType_OperationTypeId");

                            b1.HasKey("ContractAdvancePaymentId");

                            b1.ToTable("ContractAdvancePayments", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractAdvancePaymentId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.ScheduledAdvancedPayment", "Payment", b1 =>
                        {
                            b1.Property<Guid>("ContractAdvancePaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FlightsCount")
                                .HasColumnType("int")
                                .HasColumnName("FlightsCount");

                            b1.HasKey("ContractAdvancePaymentId");

                            b1.ToTable("ContractAdvancePayments", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractAdvancePaymentId");

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Money", "Balance", b2 =>
                                {
                                    b2.Property<Guid>("ScheduledAdvancedPaymentContractAdvancePaymentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Balance_Amount");

                                    b2.HasKey("ScheduledAdvancedPaymentContractAdvancePaymentId");

                                    b2.ToTable("ContractAdvancePayments", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduledAdvancedPaymentContractAdvancePaymentId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Money", "Deposit", b2 =>
                                {
                                    b2.Property<Guid>("ScheduledAdvancedPaymentContractAdvancePaymentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Deposit_Amount");

                                    b2.HasKey("ScheduledAdvancedPaymentContractAdvancePaymentId");

                                    b2.ToTable("ContractAdvancePayments", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduledAdvancedPaymentContractAdvancePaymentId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Money", "FlightCost", b2 =>
                                {
                                    b2.Property<Guid>("ScheduledAdvancedPaymentContractAdvancePaymentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("FlightCost_Amount");

                                    b2.HasKey("ScheduledAdvancedPaymentContractAdvancePaymentId");

                                    b2.ToTable("ContractAdvancePayments", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduledAdvancedPaymentContractAdvancePaymentId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Money", "RemainingBalance", b2 =>
                                {
                                    b2.Property<Guid>("ScheduledAdvancedPaymentContractAdvancePaymentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("RemainingBalance_Amount");

                                    b2.HasKey("ScheduledAdvancedPaymentContractAdvancePaymentId");

                                    b2.ToTable("ContractAdvancePayments", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduledAdvancedPaymentContractAdvancePaymentId");
                                });

                            b1.OwnsOne("Contracts.Domain.ValueObjects.Money", "RemainingDeposit", b2 =>
                                {
                                    b2.Property<Guid>("ScheduledAdvancedPaymentContractAdvancePaymentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("RemainingDeposit_Amount");

                                    b2.HasKey("ScheduledAdvancedPaymentContractAdvancePaymentId");

                                    b2.ToTable("ContractAdvancePayments", "contracts");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduledAdvancedPaymentContractAdvancePaymentId");
                                });

                            b1.Navigation("Balance")
                                .IsRequired();

                            b1.Navigation("Deposit")
                                .IsRequired();

                            b1.Navigation("FlightCost")
                                .IsRequired();

                            b1.Navigation("RemainingBalance")
                                .IsRequired();

                            b1.Navigation("RemainingDeposit")
                                .IsRequired();
                        });

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.ContractOperationType", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("OperationTypes")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Contracts.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("ContractOperationTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationType_Name");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationType_OperationTypeId");

                            b1.HasKey("ContractOperationTypeId");

                            b1.ToTable("ContractOperationTypes", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractOperationTypeId");
                        });

                    b.OwnsMany("Contracts.Domain.ValueObjects.ServiceSnapshot", "Services", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ContractOperationTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsAog")
                                .HasColumnType("bit")
                                .HasColumnName("IsAog");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ServiceId");

                            b1.HasKey("Id");

                            b1.HasIndex("ContractOperationTypeId");

                            b1.ToTable("ContractOperationTypeServices", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractOperationTypeId");
                        });

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.ContractStation", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("Stations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Contracts.Domain.ValueObjects.StationSnapshot", "Station", b1 =>
                        {
                            b1.Property<Guid>("ContractStationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Station_IataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Station_Name");

                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Station_StationId");

                            b1.HasKey("ContractStationId");

                            b1.ToTable("ContractStations", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractStationId");
                        });

                    b.Navigation("Station")
                        .IsRequired();
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.DelayBracket", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("DelayBrackets")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractGeneralSupport", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("GeneralSupports")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Contracts.Domain.Aggregates.Contract.Pricing.ContractPriceBracket", "Brackets", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BillingMode")
                                .HasColumnType("int");

                            b1.Property<int>("BlockSize")
                                .HasColumnType("int");

                            b1.Property<Guid>("ContractGeneralSupportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("MaxMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("MinMinutes")
                                .HasColumnType("int");

                            b1.Property<decimal?>("PackagePriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("PriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContractGeneralSupportId");

                            b1.ToTable("ContractGeneralSupportBrackets", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractGeneralSupportId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("ContractGeneralSupportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationType_Name");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationType_OperationTypeId");

                            b1.HasKey("ContractGeneralSupportId");

                            b1.ToTable("ContractGeneralSupports", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractGeneralSupportId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackagePaidBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractGeneralSupportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackagePaidBalance_Amount");

                            b1.HasKey("ContractGeneralSupportId");

                            b1.ToTable("ContractGeneralSupports", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractGeneralSupportId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackageRemainingBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractGeneralSupportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackageRemainingBalance_Amount");

                            b1.HasKey("ContractGeneralSupportId");

                            b1.ToTable("ContractGeneralSupports", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractGeneralSupportId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.GeneralSupportSnapshot", "GeneralSupport", b1 =>
                        {
                            b1.Property<Guid>("ContractGeneralSupportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GeneralSupportId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("GeneralSupport_GeneralSupportId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("GeneralSupport_Name");

                            b1.HasKey("ContractGeneralSupportId");

                            b1.ToTable("ContractGeneralSupports", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractGeneralSupportId");
                        });

                    b.Navigation("Brackets");

                    b.Navigation("GeneralSupport")
                        .IsRequired();

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("PackagePaidBalance");

                    b.Navigation("PackageRemainingBalance");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractManpower", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("Manpowers")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Contracts.Domain.Aggregates.Contract.Pricing.ContractPriceBracket", "Brackets", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BillingMode")
                                .HasColumnType("int");

                            b1.Property<int>("BlockSize")
                                .HasColumnType("int");

                            b1.Property<Guid>("ContractManpowerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("MaxMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("MinMinutes")
                                .HasColumnType("int");

                            b1.Property<decimal?>("PackagePriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("PriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContractManpowerId");

                            b1.ToTable("ContractManpowerBrackets", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractManpowerId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("ContractManpowerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationType_Name");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationType_OperationTypeId");

                            b1.HasKey("ContractManpowerId");

                            b1.ToTable("ContractManpowers", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractManpowerId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackagePaidBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractManpowerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackagePaidBalance_Amount");

                            b1.HasKey("ContractManpowerId");

                            b1.ToTable("ContractManpowers", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractManpowerId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackageRemainingBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractManpowerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackageRemainingBalance_Amount");

                            b1.HasKey("ContractManpowerId");

                            b1.ToTable("ContractManpowers", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractManpowerId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.ManpowerTypeSnapshot", "ManpowerType", b1 =>
                        {
                            b1.Property<Guid>("ContractManpowerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ManpowerTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ManpowerType_ManpowerTypeId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ManpowerType_Name");

                            b1.HasKey("ContractManpowerId");

                            b1.ToTable("ContractManpowers", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractManpowerId");
                        });

                    b.Navigation("Brackets");

                    b.Navigation("ManpowerType")
                        .IsRequired();

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("PackagePaidBalance");

                    b.Navigation("PackageRemainingBalance");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractMaterial", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("Materials")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Contracts.Domain.Aggregates.Contract.Pricing.ContractPriceBracket", "Brackets", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BillingMode")
                                .HasColumnType("int");

                            b1.Property<int>("BlockSize")
                                .HasColumnType("int");

                            b1.Property<Guid>("ContractMaterialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("MaxMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("MinMinutes")
                                .HasColumnType("int");

                            b1.Property<decimal?>("PackagePriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("PriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContractMaterialId");

                            b1.ToTable("ContractMaterialBrackets", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractMaterialId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("ContractMaterialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationType_Name");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationType_OperationTypeId");

                            b1.HasKey("ContractMaterialId");

                            b1.ToTable("ContractMaterials", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractMaterialId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackagePaidBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractMaterialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackagePaidBalance_Amount");

                            b1.HasKey("ContractMaterialId");

                            b1.ToTable("ContractMaterials", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractMaterialId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackageRemainingBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractMaterialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackageRemainingBalance_Amount");

                            b1.HasKey("ContractMaterialId");

                            b1.ToTable("ContractMaterials", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractMaterialId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.MaterialSnapshot", "Material", b1 =>
                        {
                            b1.Property<Guid>("ContractMaterialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MaterialId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Material_MaterialId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Material_Name");

                            b1.HasKey("ContractMaterialId");

                            b1.ToTable("ContractMaterials", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractMaterialId");
                        });

                    b.Navigation("Brackets");

                    b.Navigation("Material")
                        .IsRequired();

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("PackagePaidBalance");

                    b.Navigation("PackageRemainingBalance");
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractService", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("Services")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Contracts.Domain.ValueObjects.AircraftTypeSnapshot", "AircraftType", b1 =>
                        {
                            b1.Property<Guid>("ContractServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AircraftTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AircraftType_AircraftTypeId");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AircraftType_Model");

                            b1.HasKey("ContractServiceId");

                            b1.ToTable("ContractServices", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractServiceId");
                        });

                    b.OwnsMany("Contracts.Domain.Aggregates.Contract.Pricing.ContractPriceBracket", "Brackets", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BillingMode")
                                .HasColumnType("int");

                            b1.Property<int>("BlockSize")
                                .HasColumnType("int");

                            b1.Property<Guid>("ContractServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("MaxMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("MinMinutes")
                                .HasColumnType("int");

                            b1.Property<decimal?>("PackagePriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("PriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContractServiceId");

                            b1.ToTable("ContractServiceBrackets", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractServiceId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("ContractServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationType_Name");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationType_OperationTypeId");

                            b1.HasKey("ContractServiceId");

                            b1.ToTable("ContractServices", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractServiceId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackagePaidBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackagePaidBalance_Amount");

                            b1.HasKey("ContractServiceId");

                            b1.ToTable("ContractServices", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractServiceId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackageRemainingBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackageRemainingBalance_Amount");

                            b1.HasKey("ContractServiceId");

                            b1.ToTable("ContractServices", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractServiceId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.ServiceSnapshot", "Service", b1 =>
                        {
                            b1.Property<Guid>("ContractServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsAog")
                                .HasColumnType("bit")
                                .HasColumnName("Service_IsAog");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Service_Name");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Service_ServiceId");

                            b1.HasKey("ContractServiceId");

                            b1.ToTable("ContractServices", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractServiceId");
                        });

                    b.Navigation("AircraftType");

                    b.Navigation("Brackets");

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("PackagePaidBalance");

                    b.Navigation("PackageRemainingBalance");

                    b.Navigation("Service")
                        .IsRequired();
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Pricing.ContractTool", b =>
                {
                    b.HasOne("Contracts.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("Tools")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Contracts.Domain.ValueObjects.AircraftTypeSnapshot", "AircraftType", b1 =>
                        {
                            b1.Property<Guid>("ContractToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AircraftTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AircraftType_AircraftTypeId");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AircraftType_Model");

                            b1.HasKey("ContractToolId");

                            b1.ToTable("ContractTools", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractToolId");
                        });

                    b.OwnsMany("Contracts.Domain.Aggregates.Contract.Pricing.ContractPriceBracket", "Brackets", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BillingMode")
                                .HasColumnType("int");

                            b1.Property<int>("BlockSize")
                                .HasColumnType("int");

                            b1.Property<Guid>("ContractToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("MaxMinutes")
                                .HasColumnType("int");

                            b1.Property<int>("MinMinutes")
                                .HasColumnType("int");

                            b1.Property<decimal?>("PackagePriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("PriceValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContractToolId");

                            b1.ToTable("ContractToolBrackets", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractToolId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("ContractToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationType_Name");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationType_OperationTypeId");

                            b1.HasKey("ContractToolId");

                            b1.ToTable("ContractTools", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractToolId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackagePaidBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackagePaidBalance_Amount");

                            b1.HasKey("ContractToolId");

                            b1.ToTable("ContractTools", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractToolId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.Money", "PackageRemainingBalance", b1 =>
                        {
                            b1.Property<Guid>("ContractToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("PackageRemainingBalance_Amount");

                            b1.HasKey("ContractToolId");

                            b1.ToTable("ContractTools", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractToolId");
                        });

                    b.OwnsOne("Contracts.Domain.ValueObjects.ToolSnapshot", "Tool", b1 =>
                        {
                            b1.Property<Guid>("ContractToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Tool_Name");

                            b1.Property<Guid>("ToolId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Tool_ToolId");

                            b1.HasKey("ContractToolId");

                            b1.ToTable("ContractTools", "contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractToolId");
                        });

                    b.Navigation("AircraftType");

                    b.Navigation("Brackets");

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("PackagePaidBalance");

                    b.Navigation("PackageRemainingBalance");

                    b.Navigation("Tool")
                        .IsRequired();
                });

            modelBuilder.Entity("Contracts.Domain.Aggregates.Contract.Contract", b =>
                {
                    b.Navigation("AdvancePayments");

                    b.Navigation("CancellationBrackets");

                    b.Navigation("DelayBrackets");

                    b.Navigation("GeneralSupports");

                    b.Navigation("Manpowers");

                    b.Navigation("Materials");

                    b.Navigation("OperationTypes");

                    b.Navigation("Services");

                    b.Navigation("Stations");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
