// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operations.Infrastructure.Persistence;

#nullable disable

namespace Operations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20260707205046_Operations_FlightsOnly")]
    partial class Operations_FlightsOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operations")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Application.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ProcessedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox_messages", "operations");
                });

            modelBuilder.Entity("BuildingBlocks.Application.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("outbox_messages", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MergedIntoFlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalFlightNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid?>("PotentialDuplicateOfFlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OriginalFlightNumber");

                    b.HasIndex("Status");

                    b.ToTable("flights", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.FlightAssignedEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("flight_assigned_employees", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.FlightTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FlightId", "OccurredAtUtc");

                    b.ToTable("flight_timeline_entries", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.PlannedService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("flight_planned_services", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.Flight", b =>
                {
                    b.OwnsOne("Operations.Domain.ValueObjects.AircraftTypeSnapshot", "AircraftType", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AircraftTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AircraftTypeId");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AircraftManufacturer");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("AircraftModel");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.CustomerSnapshot", "Customer", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CustomerId");

                            b1.Property<string>("IataCode")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("CustomerIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CustomerName");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.FlightNumber", "FlightNumber", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("FlightNumber");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationTypeName");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationTypeId");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.ScheduledTime", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Sta")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ScheduledArrivalUtc");

                            b1.Property<DateTimeOffset>("Std")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ScheduledDepartureUtc");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.StationSnapshot", "Station", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("StationIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("StationName");

                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StationId");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.Navigation("AircraftType");

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("FlightNumber")
                        .IsRequired();

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Station")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Flights.FlightAssignedEmployee", b =>
                {
                    b.HasOne("Operations.Domain.Flights.Flight", null)
                        .WithMany("AssignedEmployees")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.StaffMemberSnapshot", "Employee", b1 =>
                        {
                            b1.Property<Guid>("FlightAssignedEmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("StaffEmployeeId");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("StaffFullName");

                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StaffMemberId");

                            b1.HasKey("FlightAssignedEmployeeId");

                            b1.ToTable("flight_assigned_employees", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightAssignedEmployeeId");
                        });

                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Flights.PlannedService", b =>
                {
                    b.HasOne("Operations.Domain.Flights.Flight", null)
                        .WithMany("PlannedServices")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.ServiceSnapshot", "Service", b1 =>
                        {
                            b1.Property<Guid>("PlannedServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ServiceName");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ServiceId");

                            b1.HasKey("PlannedServiceId");

                            b1.ToTable("flight_planned_services", "operations");

                            b1.WithOwner()
                                .HasForeignKey("PlannedServiceId");
                        });

                    b.Navigation("Service")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Flights.Flight", b =>
                {
                    b.Navigation("AssignedEmployees");

                    b.Navigation("PlannedServices");
                });
#pragma warning restore 612, 618
        }
    }
}
