// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operations.Infrastructure.Persistence;

#nullable disable

namespace Operations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    partial class OperationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operations")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Application.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ProcessedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox_messages", "operations");
                });

            modelBuilder.Entity("BuildingBlocks.Application.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("outbox_messages", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MergedIntoFlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalFlightNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid?>("PotentialDuplicateOfFlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OriginalFlightNumber");

                    b.HasIndex("Status");

                    b.ToTable("flights", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.FlightAssignedEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("flight_assigned_employees", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.PlannedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("flight_planned_services", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Sequences.StationWorkOrderSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LastValue")
                        .HasColumnType("int");

                    b.Property<string>("StationIata")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("station_work_order_sequences", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AircraftTailNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerSignatureReference")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersededByWorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("Status");

                    b.ToTable("work_orders", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderServiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<bool>("ReturnToRamp")
                        .HasColumnType("bit");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("work_order_service_lines", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderServiceLineEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceLineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceLineId");

                    b.ToTable("work_order_service_line_employees", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("ReturnToRamp")
                        .HasColumnType("bit");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("work_order_tasks", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("work_order_task_attachments", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("work_order_task_employees", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskGeneralSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("work_order_task_general_supports", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("work_order_task_materials", "operations");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("work_order_task_tools", "operations");
                });

            modelBuilder.Entity("Operations.Domain.Flights.Flight", b =>
                {
                    b.OwnsOne("Operations.Domain.ValueObjects.AircraftTypeSnapshot", "AircraftType", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AircraftTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AircraftTypeId");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AircraftManufacturer");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("AircraftModel");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.CustomerSnapshot", "Customer", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CustomerId");

                            b1.Property<string>("IataCode")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("CustomerIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CustomerName");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.FlightNumber", "FlightNumber", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("FlightNumber");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationTypeName");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationTypeId");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.ScheduledTime", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Sta")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ScheduledArrivalUtc");

                            b1.Property<DateTimeOffset>("Std")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ScheduledDepartureUtc");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.StationSnapshot", "Station", b1 =>
                        {
                            b1.Property<Guid>("FlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("StationIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("StationName");

                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StationId");

                            b1.HasKey("FlightId");

                            b1.ToTable("flights", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.Navigation("AircraftType");

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("FlightNumber")
                        .IsRequired();

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Station")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Flights.FlightAssignedEmployee", b =>
                {
                    b.HasOne("Operations.Domain.Flights.Flight", null)
                        .WithMany("AssignedEmployees")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.StaffMemberSnapshot", "Employee", b1 =>
                        {
                            b1.Property<Guid>("FlightAssignedEmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("StaffEmployeeId");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("StaffFullName");

                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StaffMemberId");

                            b1.HasKey("FlightAssignedEmployeeId");

                            b1.ToTable("flight_assigned_employees", "operations");

                            b1.WithOwner()
                                .HasForeignKey("FlightAssignedEmployeeId");
                        });

                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Flights.PlannedService", b =>
                {
                    b.HasOne("Operations.Domain.Flights.Flight", null)
                        .WithMany("PlannedServices")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.ServiceSnapshot", "Service", b1 =>
                        {
                            b1.Property<Guid>("PlannedServiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ServiceName");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ServiceId");

                            b1.HasKey("PlannedServiceId");

                            b1.ToTable("flight_planned_services", "operations");

                            b1.WithOwner()
                                .HasForeignKey("PlannedServiceId");
                        });

                    b.Navigation("Service")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.OwnsOne("Operations.Domain.ValueObjects.ActualTime", "Actuals", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Ata")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ActualArrivalUtc");

                            b1.Property<DateTimeOffset>("Atd")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ActualDepartureUtc");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.CancellationDetails", "Cancellation", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("CanceledAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CanceledAtUtc");

                            b1.Property<Guid>("CanceledByUserId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CanceledByUserId");

                            b1.Property<string>("Reason")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("CancellationReason");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.WorkOrderNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("WorkOrderNumber");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.AircraftTypeSnapshot", "AircraftType", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AircraftTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AircraftTypeId");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AircraftManufacturer");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("AircraftModel");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.CustomerSnapshot", "Customer", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CustomerId");

                            b1.Property<string>("IataCode")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("CustomerIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CustomerName");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.FlightNumber", "FlightNumber", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("FlightNumber");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.OperationTypeSnapshot", "OperationType", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OperationTypeName");

                            b1.Property<Guid>("OperationTypeId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OperationTypeId");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.ScheduledTime", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Sta")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ScheduledArrivalUtc");

                            b1.Property<DateTimeOffset>("Std")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ScheduledDepartureUtc");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.StationSnapshot", "Station", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IataCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("StationIataCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("StationName");

                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StationId");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("work_orders", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.Navigation("Actuals");

                    b.Navigation("AircraftType");

                    b.Navigation("Cancellation");

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("FlightNumber")
                        .IsRequired();

                    b.Navigation("Number");

                    b.Navigation("OperationType")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Station")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderServiceLine", b =>
                {
                    b.HasOne("Operations.Domain.WorkOrders.WorkOrder", null)
                        .WithMany("ServiceLines")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.ServiceSnapshot", "Service", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderServiceLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ServiceName");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ServiceId");

                            b1.HasKey("WorkOrderServiceLineId");

                            b1.ToTable("work_order_service_lines", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderServiceLineId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.TimeWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderServiceLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("FromUtc");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ToUtc");

                            b1.HasKey("WorkOrderServiceLineId");

                            b1.ToTable("work_order_service_lines", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderServiceLineId");
                        });

                    b.Navigation("Service")
                        .IsRequired();

                    b.Navigation("Window")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderServiceLineEmployee", b =>
                {
                    b.HasOne("Operations.Domain.WorkOrders.WorkOrderServiceLine", null)
                        .WithMany("Employees")
                        .HasForeignKey("ServiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.StaffMemberSnapshot", "Employee", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderServiceLineEmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("StaffEmployeeId");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("StaffFullName");

                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StaffMemberId");

                            b1.HasKey("WorkOrderServiceLineEmployeeId");

                            b1.ToTable("work_order_service_line_employees", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderServiceLineEmployeeId");
                        });

                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTask", b =>
                {
                    b.HasOne("Operations.Domain.WorkOrders.WorkOrder", null)
                        .WithMany("Tasks")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.TimeWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("FromUtc");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ToUtc");

                            b1.HasKey("WorkOrderTaskId");

                            b1.ToTable("work_order_tasks", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskId");
                        });

                    b.Navigation("Window")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskAttachment", b =>
                {
                    b.HasOne("Operations.Domain.WorkOrders.WorkOrderTask", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskEmployee", b =>
                {
                    b.HasOne("Operations.Domain.WorkOrders.WorkOrderTask", null)
                        .WithMany("Employees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.StaffMemberSnapshot", "Employee", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskEmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("StaffEmployeeId");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("StaffFullName");

                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("StaffMemberId");

                            b1.HasKey("WorkOrderTaskEmployeeId");

                            b1.ToTable("work_order_task_employees", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskEmployeeId");
                        });

                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskGeneralSupport", b =>
                {
                    b.HasOne("Operations.Domain.WorkOrders.WorkOrderTask", null)
                        .WithMany("GeneralSupports")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.GeneralSupportSnapshot", "GeneralSupport", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskGeneralSupportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GeneralSupportId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("GeneralSupportId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("GeneralSupportName");

                            b1.HasKey("WorkOrderTaskGeneralSupportId");

                            b1.ToTable("work_order_task_general_supports", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskGeneralSupportId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskGeneralSupportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("Quantity");

                            b1.HasKey("WorkOrderTaskGeneralSupportId");

                            b1.ToTable("work_order_task_general_supports", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskGeneralSupportId");
                        });

                    b.Navigation("GeneralSupport")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskMaterial", b =>
                {
                    b.HasOne("Operations.Domain.WorkOrders.WorkOrderTask", null)
                        .WithMany("Materials")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.MaterialSnapshot", "Material", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskMaterialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MaterialId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("MaterialId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MaterialName");

                            b1.HasKey("WorkOrderTaskMaterialId");

                            b1.ToTable("work_order_task_materials", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskMaterialId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskMaterialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("Quantity");

                            b1.HasKey("WorkOrderTaskMaterialId");

                            b1.ToTable("work_order_task_materials", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskMaterialId");
                        });

                    b.Navigation("Material")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTaskTool", b =>
                {
                    b.HasOne("Operations.Domain.WorkOrders.WorkOrderTask", null)
                        .WithMany("Tools")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Operations.Domain.ValueObjects.ToolSnapshot", "Tool", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ToolName");

                            b1.Property<Guid>("ToolId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ToolId");

                            b1.HasKey("WorkOrderTaskToolId");

                            b1.ToTable("work_order_task_tools", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskToolId");
                        });

                    b.OwnsOne("Operations.Domain.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderTaskToolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("Quantity");

                            b1.HasKey("WorkOrderTaskToolId");

                            b1.ToTable("work_order_task_tools", "operations");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderTaskToolId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Tool")
                        .IsRequired();
                });

            modelBuilder.Entity("Operations.Domain.Flights.Flight", b =>
                {
                    b.Navigation("AssignedEmployees");

                    b.Navigation("PlannedServices");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Navigation("ServiceLines");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderServiceLine", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Operations.Domain.WorkOrders.WorkOrderTask", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Employees");

                    b.Navigation("GeneralSupports");

                    b.Navigation("Materials");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
